name: plproject
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.6 # NEW: For opening maps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # CORRECTED: Use the version compatible with the Flutter SDK
  intl: ^0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/
  - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700